---
title: "Conferencia: Perspectivas globales"
format:
  html:
    body-classes: program-page
    page-layout: custom
    main-container: default
    toc: false
    include-before-body: _sidebar-programa.html
    include-after-body: _sidebar-programa-close.html
---

<br><br><br>

# Bienvenida

Equipo Organizador de Abre tu Ciencia 2026: Magdalena Gatsch, José Daniel Conejeros, María Spencer-Sandino, Estela Blanco; Eduardo Undurraga.  

<a href="#" class="material-link" target="_blank"><i class="fas fa-file-powerpoint"></i> Presentación</a>


# Conferencia Magistral: Perspectivas globales en reproducibilidad y transparencia

**Fecha:** 22 de Enero, 2026

**Horario:** 09:00 am - 10:00 am

Esta conferencia magistral explora las perspectivas globales sobre reproducibilidad y transparencia en la investigación científica, abordando los desafíos y oportunidades que enfrentan investigadores e instituciones en la promoción de prácticas de ciencia abierta. Se discutirán estándares internacionales, marcos normativos y estrategias para fortalecer la credibilidad y el impacto de la investigación a través de la transparencia metodológica y la reproducibilidad de resultados.

**Expositor:** José Antonio Muñoz

**Materiales**

<a href="#" class="material-link" target="_blank"><i class="fas fa-file-powerpoint"></i> Presentación</a>
<a href="#" class="material-link" target="_blank"><i class="fas fa-folder-open"></i> Materiales</a>
<a href="#" class="material-link" target="_blank"><i class="fab fa-github"></i> Código</a>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>