---
title: "Laboratorio 4: Git y GitHub"
format:
  html:
    body-classes: program-page
    page-layout: custom
    main-container: default
    toc: false
    include-before-body: _sidebar-programa.html
    include-after-body: _sidebar-programa-close.html
---

<br><br><br>

# Laboratorio 4: Control de versiones y repositorios en Git y GitHub

**Fecha:** 22 de Enero, 2026

**Horario:** 02:00 pm - 03:00 pm


Este laboratorio práctico ilustra el uso de Git y GitHub como herramientas clave para el desarrollo de proyectos abiertos y reproducibles. Sus participantes aprenderán a organizar repositorios para compartir código o datos y documentar adecuadamente su trabajo. Además, se revvisará cómo convertir estos repositorios en outputs de investigación citables mediante buenas prácticas de publicación, licenciamiento y vinculación con identificadores persistentes. 
El laboratorio supone un conocimiento básico de Git y GitHub (por ejemplo, saber cómo hacer _push_ y _pull_ en un repositorio propio).

**Materiales**

**Expositora:** Riva Quiroga

<a href="#" class="material-link" target="_blank"><i class="fas fa-file-powerpoint"></i> Presentación</a>
<a href="#" class="material-link" target="_blank"><i class="fas fa-folder-open"></i> Materiales</a>
<a href="#" class="material-link" target="_blank"><i class="fab fa-github"></i> Código</a>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
